name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: 7.1
            phpstan-version: "1.4"
          - php-version: 8.4
            phpstan-version: "2.1"
    name: PHP ${{ matrix.php-version }} - phpstan ${{ matrix.phpstan-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist
          composer remove phpstan/phpstan --dev || true

          composer require --dev phpstan/phpstan:^${{ matrix.phpstan-version }} --no-interaction || true
          fi

      - name: Run PHPStan
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse src --level=max || true
          else
            echo "phpstan not installed for this combination, skipping"
          fi
