name: PHPStan Analysis

on:
  push:
    branches: test 
  pull_request:
    branches: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: 7.1
            phpstan-version: "1.4"
          - php-version: 8.4
            phpstan-version: "2.1"
    name: PHP ${{ matrix.php-version }} - phpstan ${{ matrix.phpstan-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          composer remove phpstan/phpstan --dev || true
          composer require --dev phpstan/phpstan:^${{ matrix.phpstan-version }} --no-interaction || true

      - name: Run PHPStan
        run: |
          if [ -f vendor/bin/phpstan ]; then
            if [ -d src ]; then
              vendor/bin/phpstan analyse src --level=max || true
            else
              vendor/bin/phpstan analyse . --level=max || true
            fi
          else
            echo "phpstan not installed for this combination, skipping"
          fi
